// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Read a DB URL from env: trim, strip accidental quotes/newlines, ignore empty.
 * Prisma expects `postgresql://` (normalize `postgres://`).
 */
function readConnectionUrl(varName: string): string | undefined {
  const raw = process.env[varName];
  if (raw == null) return undefined;
  let s = raw.trim().replace(/\r\n|\r|\n/g, "");
  if (s.length === 0) return undefined;
  if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'"))) {
    s = s.slice(1, -1).trim();
  }
  if (s.length === 0) return undefined;
  if (s.startsWith("postgres://") && !s.startsWith("postgresql://")) {
    s = `postgresql://${s.slice("postgres://".length)}`;
  }
  return s;
}

/** Migrations: prefer direct Neon URL; must not be empty or Prisma gets P1013. */
function migrationDatabaseUrl(): string | undefined {
  return readConnectionUrl("DIRECT_URL") ?? readConnectionUrl("DATABASE_URL");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrationDatabaseUrl(),
  },
});
